print("programujemy \n w Pythonie")
print("i nie tylko")
print("to jest dodawanie", 23+5)
a = int(input('Podaj pierwszą liczbę\n'))
b = int(input('Podaj drugą liczbę\n'))
print("Twoj wynik:", a*b)
input("\n\n Aby zakonczyc, nacisnij ENTER")